// <auto-generated />
namespace Aplicacao.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inicial_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201809172206076_inicial_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
