// <auto-generated />
namespace Aplicacao.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_));
        
        string IMigrationMetadata.Id
        {
            get { return "201809191533527_remove_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
